version: '3'
services:
  app:
    image: myapp:latest
    container_name: myapp
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
    volumes:
      - .:/usr/src/app
    depends_on:
      - db

  db:
