version: '3'
services:
  app:
    image: myapp:latest
    container_name: myapp
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
    volumes:
      - .:/usr/src/app
    depends_on:
      - db

  db:
    image: mongo:latest
    container_name: my-ap-db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - db-data:/data/db

  volumes:
    db-data:
